production:
    urlRoot: https://example.com/mmlxr
    _port: 8001
    enableDemo: false
    github:
        clientId: xxxxxxxxxxxxxxxxxxxx
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    googleDrive:
        clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxx
        browserKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        scope: 'https://www.googleapis.com/auth/drive.file'
    googleAnalytics:
        trackingId: UA-xxxxxxxx-x
staging:
    urlRoot: https://example.com/mmlxr-staging
    _port: 8000
    _basicAuth:
        _user: xxxxxxxx
        _pass: xxxxxxxx
    enableDemo: false
    github:
        clientId: xxxxxxxxxxxxxxxxxxxx
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    googleDrive:
        clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxx
        browserKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        scope: 'https://www.googleapis.com/auth/drive.file'
develop:
    urlRoot: http://localhost:8000
    _port: 8000
    enableDemo: true
    github:
        clientId: xxxxxxxxxxxxxxxxxxxx
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    googleDrive:
        clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
        _clientSecret: xxxxxxxxxxxxxxxxxxxxxxxx
        browserKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        scope: 'https://www.googleapis.com/auth/drive.file'
